### ISSUE TITLE
branch with 3.2 support

### ISSUE THREAD

**Issue by MichaelBelousov** [rakai93/godot_voronoi#9]
would you accept a PR for a branch with 3.2 support?

**Comment by rakai93** [comment]
Of course. I personally don't use this extension right now, but if you provide the PR, I'm happy to merge it.

**Comment by MichaelBelousov** [comment]
I would like to do it soon (I already have in my fork, just need to make the PR ofc), it's really a tiny tiny change but may help other people who want to use it, if someone needs it and I haven't done it yet please ping me here

**Comment by rakai93** [comment]
Since I'm back using Godot again, I tried your 3.2-support branch, but it does not compile. This code still works properly with the 3.2.3-stable version.
